[package]
name = "pngeu"
author = "euds63"
about = "an implementation of https://picklenerd.github.io/pngme_book/"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
crc = "3.0.1"
